### ISSUE TITLE
Update default version of Kibana to 7.10.2

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/kibana-buildpack#10]
Current default version of KIbana: 6.6.1
Latest version of Kibana 7.x: https://artifacts.elastic.co/downloads/kibana/kibana-7.15.1-linux-x86_64.tar.gz

**Comment by EtienneM** [comment]
Hello @josephpage 

From what we understand, Kibana 7.10.2 is indeed still using the Apache license (https://github.com/elastic/kibana/blob/v7.10.2/LICENSE.txt), and Logstash 7.17.9 is also under the Apache license (https://github.com/elastic/logstash/blob/v7.17.9/LICENSE.txt). Hence we would happily welcome a contribution for these updates :)
